import { motion } from "framer-motion";
import { useParams } from "react-router-dom";

const ARTICLE = {
  slug: "advantages-of-body-scan-with-3d-technology",
  label: "ARTICLES",
  title: "The Advantages of Body Scan with 3D Technology",
  intro: ` The body scan with 3D technology has arrived in the constantly changing world of health, fitness, and wellness as a game-changing innovation. This technology has the potential to revolutionize this field for individuals, athletes, and businesses alike. By utilizing advanced algorithms, 3Dbody scanners provide a comprehensive and precise analysis of our physical composition, this groundbreaking technology has completely transformed how we perceive and understand our bodies. The benefits of body scanning with 3D technology are reshaping various aspects of our lives, including enhancing athletic performance, improving healthcare diagnostics, advancing personalized fitness and nutrition plans, optimizing garment and fashion design, and promoting body positivity and self-image`,
  heroImage: "/Untitled.png",

  sections: [
    {
      heading: "Accurate and Detailed Body Measurements",
      body: `By combining the benefits of accurate and detailed body measurements, advanced 3D body scanning technology empowers athletes to have a clear understanding of their body composition. The insights provided by these scanners enable athletes to set specific goals, track their progress effectively, and make informed decisions about their nutrition, training focus, and overall performance. With access to precise measurements, athletes can fine-tune their training and nutrition plans to optimize their performance and achieve their desired outcomes. The detailed information offered by advanced 3D body scanning technology revolutionizes the way athletes approach their training and empowers them to reach new levels of success.`,
    },
    {
      heading: "The Role of 3D Body Scanning Technology in Injury Prevention and Rehabilitation",
      body: `By utilizing the detailed reports and data generated by these scanners, coaches and medical professionals can effectively identify potential risk factors, such as muscle imbalances or postural issues, that may contribute to injuries. Through a thorough analysis of the scanned data, muscular imbalances, asymmetries, or areas of weakness can be pinpointed, helping identify potential injury-prone areas for athletes. Armed with this knowledge, coaches and medical professionals can design targeted exercises, corrective programs, and personalized rehabilitation plans to address these issues, promoting injury prevention and facilitating effective recovery. For example, by implementing tailored strength training exercises to correct imbalances or prescribing specific stretching routines to improve flexibility, athletes can enhance their overall performance and ensure longevity in their respective sports. This utilization of 3D body scan in injury prevention and rehabilitation demonstrates its value in optimizing athlete health and performance.`,
      image: "/back.png",
      imageAlt: "Injury prevention and rehabilitation",
    },
    {
      heading: "Tracking performance metrics over time using body scan",
      body: `Another benefit of body scan for athletes is its ability to track performance metrics over time. This tracking enables athletes to evaluate the effectiveness of their training programs and make necessary adjustments to optimize their performance. By regularly scanning their bodies using PT 3Dfit, athletes can monitor changes in muscle mass, body fat percentage, water percentage, basal metabolic rate, visceral fat, and other relevant parameters. Additionally, it provides valuable insights into the impact of factors such as nutrition, recovery, and lifestyle choices on their athletic progress. `,
      image: "/mirror.png",
      imageAlt: "Tracking progress over time",
    },
    {
      heading: "Psychological and Emotional Well-being",
      body: `Beyond the physical benefits, 3D body scanning can positively impact an athlete's mental and emotional well-being. These scans provide athletes with an objective view of their bodies, fostering a healthier body image, boosting self-confidence, and improving overall mental outlook. This positive mindset has a profound influence on an athlete's performance, allowing them to compete with greater focus, determination, and resilience. `,
    },
    {
      heading: "Assessing Athletic Potential Utilizing 3D Body Scan Technology",
      body: `Athletes are often selected for specific sports based on a comparison of their body size and shape with the general population. For instance, elite rowers exhibit distinct characteristics in their 3D body scans, with top male rowers typically having larger chests and elite female rowers having larger thigh muscles. Marathon runners tend to have longer legs in proportion to their torso length and maintain a leaner physique compared to the average person. These observations highlight how specific body traits can play a significant role in determining an athlete's suitability for particular sports.`,
    },
    {
      heading: "Conclusion",
      body: `Assessing athletic potential plays a crucial role in determining an athlete's suitability for specific sports. With the advent of 3D body scan technology, coaches and sports scientists now have a powerful tool at their disposal. By utilizing advanced scanning techniques, body scan technology provides a detailed and comprehensive analysis of an athlete's body composition. These scans reveal specific characteristics and traits that are often associated with excellence in certain sports, enabling a more precise assessment of an athlete's athletic potential.
`,
    },
  ],
};

const ArticleDetail = () => {
  const { slug } = useParams();

  if (slug !== ARTICLE.slug) {
    return (
      <div className="container py-24">
        <p className="text-muted-foreground">Article not found.</p>
      </div>
    );
  }

  return (
    <div className="bg-background">
      <section className="py-16 md:py-20">
        <div className="container">
          <motion.div
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            className="max-w-4xl mx-auto"
          >
            <div className="text-secondary text-xs font-semibold uppercase tracking-wider">
              {ARTICLE.label}
            </div>

            <h1 className="mt-3 text-3xl md:text-5xl font-heading font-bold text-foreground">
              {ARTICLE.title}
            </h1>

            <div className="mt-4 h-px w-12 bg-muted-foreground/30" />

            <p className="mt-6 text-muted-foreground leading-relaxed">
              {ARTICLE.intro}
            </p>

            <div className="mt-10">
              <img
                src={ARTICLE.heroImage}
                alt="3D body scanning"
                className="w-full max-w-3xl mx-auto rounded-lg"
                loading="lazy"
              />
            </div>

            <div className="mt-14 space-y-12">
              {ARTICLE.sections.map((s) => (
                <div key={s.heading}>
                  <h2 className="text-secondary text-xl md:text-2xl font-heading font-semibold">
                    {s.heading}
                  </h2>

                  <p className="mt-3 text-muted-foreground leading-relaxed">
                    {s.body}
                  </p>

                  {"image" in s && s.image ? (
                    <div className="mt-8">
                      <img
                        src={s.image}
                        alt={s.imageAlt || s.heading}
                        className="w-full max-w-2xl mx-auto rounded-lg"
                        loading="lazy"
                      />
                    </div>
                  ) : null}
                </div>
              ))}
            </div>

            {/* Optional bottom spacing like screenshot */}
            <div className="mt-16 h-px w-12 bg-muted-foreground/20 mx-auto" />
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default ArticleDetail;