import React from "react";

export type SubSection = {
  title: string;
  paragraphs: React.ReactNode[];
};

export type Section = {
  heading: string;
  paragraphs: React.ReactNode[];
  image?: string;
  imageAlt?: string;
  imageMaxWidth?: string;
  subSections?: SubSection[];
  
};

export type Article = {
  slug: string;
  label: string;
  title: string;
  author: string;
  date: string;
  category: string;
  excerpt: string;

  coverImage: string;
  coverImageAlt?: string;
  

  // detail page content
  introParagraphs: React.ReactNode[];
  heroImage?: string;
  heroImageAlt?: string;
  sections: Section[];
};

export const ARTICLES: Article[] = [
  // ✅ ARTICLE 1: Body Scan
  {
    slug: "advantages-of-body-scan-with-3d-technology",
    label: "ARTICLES",
    title: "The Advantages of Body Scan with 3D Technology",
    author: "PT 3Dfit Team",
    date: "Jan 15, 2026",
    category: "Articles",

    coverImage: "/Untitled.png",
coverImageAlt: "3D body scan",

    excerpt:
      "Discover how 3D body scanning provides precise measurements, supports performance tracking, helps injury prevention, and improves overall well-being.",

    introParagraphs: [
      `The body scan with 3D technology has arrived in the constantly changing world of health, fitness, and wellness as a game-changing innovation. This technology has the potential to revolutionize this field for individuals, athletes, and businesses alike. By utilizing advanced algorithms, 3D body scanners provide a comprehensive and precise analysis of our physical composition. The benefits of body scanning with 3D technology are reshaping various aspects of our lives, including enhancing athletic performance, improving healthcare diagnostics, advancing personalized fitness and nutrition plans, optimizing garment and fashion design, and promoting body positivity and self-image.`,
    ],

    heroImage: "/Untitled.png",
    heroImageAlt: "3D body scan",

    sections: [
      {
        heading: "Accurate and Detailed Body Measurements",
        paragraphs: [
          `By combining the benefits of accurate and detailed body measurements, advanced 3D body scanning technology empowers athletes to have a clear understanding of their body composition. The insights provided by these scanners enable athletes to set specific goals, track their progress effectively, and make informed decisions about their nutrition, training focus, and overall performance.`,
        ],
      },
      {
        heading: "The Role of 3D Body Scanning Technology in Injury Prevention and Rehabilitation",
        paragraphs: [
          `By utilizing the detailed reports and data generated by these scanners, coaches and medical professionals can identify potential risk factors, such as muscle imbalances or postural issues, that may contribute to injuries. This helps design targeted exercises, corrective programs, and personalized rehabilitation plans to promote injury prevention and recovery.`,
        ],
        image: "/back.png",
        imageAlt: "Injury prevention and rehabilitation",
      },
      {
        heading: "Tracking performance metrics over time using body scan",
        paragraphs: [
          `Another benefit of body scan for athletes is its ability to track performance metrics over time. By regularly scanning their bodies, athletes can monitor changes in muscle mass, body fat percentage, water percentage, basal metabolic rate, visceral fat, and other relevant parameters.`,
        ],
        image: "/mirror.png",
        imageAlt: "Tracking progress over time",
      },
      {
        heading: "Psychological and Emotional Well-being",
        paragraphs: [
          `Beyond the physical benefits, 3D body scanning can positively impact an athlete's mental and emotional well-being by providing an objective view of the body and boosting self-confidence.`,
        ],
      },
      {
        heading: "Assessing Athletic Potential Utilizing 3D Body Scan Technology",
        paragraphs: [
          `Athletes are often selected for specific sports based on a comparison of their body size and shape with the general population. These observations highlight how specific body traits can play a significant role in determining an athlete's suitability for particular sports.`,
        ],
      },
      {
        heading: "Conclusion",
        paragraphs: [
          `With the advent of 3D body scan technology, coaches and sports scientists now have a powerful tool for a detailed and comprehensive analysis of an athlete's body composition, enabling a more precise assessment of athletic potential.`,
        ],
      },
    ],
  },


  {
    slug: "foot-pressure-scan-best-type-of-foot-scan",
    label: "ARTICLES",
    title: "Foot Pressure Scan | Best Type of Foot Scan",
    author: "Payatek Team",
    date: "Jan 16, 2026",
    category: "Articles",

    coverImage: "/Foot-2.png",
coverImageAlt: "3D body scan",

    
    excerpt:
      "Learn how pressure platform scanning captures plantar pressure distribution, supports diagnosis, and improves treatment outcomes.",

    introParagraphs: [
      `The best type of foot scan involves using a pressure platform with tactile sensors to capture all characteristics of the foot and analyze its function. Foot Pressure scan is done to measure and analyze a person’s feet while they are performing activities such as walking, running, and standing. It produces a clear picture of the pressure applied to each part of the foot sole and can determine the exact location of any extra pressure on the foot.`,
      <>
        The contents and facilities in this article are described according to the facilities available in{" "}
        <a className="text-secondary underline" href="#" onClick={(e) => e.preventDefault()}>
          Payatek’s PT-SCAN foot pressure scanner
        </a>
        .
      </>,
    ],

    // if you want a hero image at top, set it; otherwise leave undefined
    // heroImage: "/pressure-hero.png",
    // heroImageAlt: "Foot pressure scan hero",

    sections: [
      {
        heading: "How is the plantar scan performed with the foot pressure scanner?",
        paragraphs: [
          `Scanning the sole of the foot with a foot pressure scanner is a very simple, comprehensive, and reliable method that requires only a few minutes to perform.`,
          `The pressure scanner is connected to the computer, and information about the foot pressure distribution is displayed.`,
          `Various diagrams of this device provide a detailed description and interpretation of foot health and the characteristics of a person’s steps.`,
        ],
        image: "/Pressure-0.png",
        imageAlt: "Pressure sensing mat",
        imageMaxWidth: "max-w-xl",
      },
      {
        heading: "Why should a foot scan be done with a foot pressure scanner?",
        paragraphs: [
          `You may be surprised by the process of scanning with a foot pressure scanner. This process has several advantages, and being aware of them will help you.`,
        ],
        subSections: [
          {
            title: "Simple performing for the patient",
            paragraphs: [
              `This test is performed on patients by having them walk and stand on a flat surface. There is no need to place the foot in a special position on the device.`,
            ],
          },
          {
            title: "Accurate and comprehensive analysis",
            paragraphs: [
              `The analysis is very accurate and comprehensive, showing detailed distribution of weight bearing, point-by-point pressure, and a comparison between the two feet.`,
            ],
          },
        ],
      },
      {
        heading: "Evaluate the position of the body’s center of force",
        paragraphs: [
          `The body’s center of force is evaluated by scanning while standing and walking. This is an accurate tool to assess lower limbs and identify musculoskeletal issues.`,
        ],
      },
      {
        heading: "Kinesiology diagrams and monitoring the treatment process",
        paragraphs: [
          `Foot pressure scanning with a pressure mat provides a comprehensive study of kinesiology. It helps compare treatment effectiveness and aids such as orthotic insoles and braces.`,
        ],
      },
      {
        heading: "Examining chronic and localized pains",
        paragraphs: [
          `Chronic pains in the foot sole can be assessed using a foot pressure scanner. Orthotic insoles can be made according to the results of the foot scan during walking.`,
        ],
      },
      {
        heading: "Is the foot pressure scanner providing us with accurate data?",
        paragraphs: [
          `Foot pressure must be applied to a platform in order to capture the foot pressure. Pressure sensors are therefore required.`,
          `For more accurate results, foot scanning should be performed while walking (gait cycle), too.`,
        ],
        image: "/Pressure-1.png",
        imageAlt: "Feet on foot pressure scanner",
        imageMaxWidth: "max-w-3xl",
      },
      {
        heading: "Foot pressure scanning and back pain",
        paragraphs: [
          <>
            The cause of many back pains is an unbalanced distribution of pressure in the feet. Therefore, it is necessary to
            analyze the foot pressure with a{" "}
            <a className="text-secondary underline" href="#" onClick={(e) => e.preventDefault()}>
              foot pressure scanner
            </a>
            .
          </>,
        ],
      },
      {
        heading: "Foot pressure scanning for peripheral neuropathy",
        paragraphs: [
          `Foot pressure has a direct impact on how you walk. A foot scan with a foot pressure scanner is important for the evaluation of patients with peripheral neuropathy and can provide necessary information to treat the patient.`,
        ],
      },
      {
        heading: "Foot scan for lower limb and foot pain",
        paragraphs: [
          `A foot pressure scanner can provide necessary information about pressure distribution, allowing specialists to prescribe treatment and relieve pain.`,
        ],
      },
      {
        heading: "Scanning the athlete’s feet",
        paragraphs: [
          `Performing a scan with a foot pressure scanner is extremely important for athletes to increase awareness of pressure distribution and improve performance while reducing injury risk.`,
        ],
      },
    ],
  },

  {
  slug: "foot-scanner-types",
  label: "ARTICLES",
  title: "Foot Scanner Types",
  author: "Payatek Team",
  date: "Jan 17, 2026",
  category: "Articles",

  coverImage: "/Foot-5.png",
  coverImageAlt: "3D body scan",
 
  excerpt:
    "Learn the differences between optical foot scanners, foot pressure scanners, gait analysis systems, and 3D foot scanners — plus how to choose the right one.",

  introParagraphs: [
    `Nowadays, foot scanner is used in foot health clinics for the purpose of foot scanning, from the simplest ones (digital podoscope) to the most advanced ones. Each of these devices has advantages and limitations. Specialists and patients should be aware of the characteristics and proper use of each device in diagnosing and treating patients’ foot problems.`,
    `Choosing efficient and accurate instruments has more benefits, such as make a faster and more precise diagnosis, have patient satisfaction and get the most efficient treatment.`,
    `In the following we will describe the differences and applications of types of foot scanners.`,
  ],

  sections: [
    {
      heading: "1. What equipment do we have to scan the foot?",
      paragraphs: [],
      subSections: [
        {
          title: "What is the application of different foot scanners?",
          paragraphs: [
            `Foot scanning equipment is divided into three general categories:`,
          ],
        },
      ],
    },

    {
      heading: "1.1 Optical Foot Scanner",
      paragraphs: [
        `Optical foot scanners have a simple technology and consist of a glass screen, a light source, and a camera. Function of these scanners is similar to that of paper scanners, and they are used to check the foot arch type just in standing and also measure the dimensions of the foot.`,
      ],
      image: "/Foot-0.png",
      imageAlt: "Optical foot scanner",
      imageMaxWidth: "max-w-2xl",
      subSections: [
        {
          title: "",
          paragraphs: [
            `Patient stands on a glass surface. The scanner scans or captures the reflected image of the patient’s feet.`,
            `As you know and probably observed, if you press your finger on a surface, the skin contact with the surface will turn white.`,
            `This is the principle that optical foot scanner use to measure pressure.`,
            `The greater pressure of the foot area on the ground makes the color of that part of the sole closer to white.`,
            `By detecting the change in foot sole color, the areas that bear more weight and put more pressure on the ground are identified.`,
            `But the accuracy of optical foot scanners in detecting high pressure points is low and they do not have the ability to scan the foot while walking and are limited to standing.`,
          ],
        },
        {
          title: "Advantages of the optical foot scanner:",
          paragraphs: [
            "• Determining the size of the patient’s foot",
            "• Identifying the foot arch type in standing position",
          ],
        },
        {
          title: "Disadvantages of optical foot scanner:",
          paragraphs: [
            "• Failure to accurately measure the pressure on the foot sole and failure to measure point by point pressure in different regions of the foot sole; as a result, it isn’t proper for diabetic foot analysis.",
            "• It is not possible to distinguish a rigid flat foot from a flexible flat foot",
            "• Inability to analyze the foot while walking (dynamics)",
            "• The impossibility of simulating different foot parts and detecting possible injuries due to the failure to perform the walking test",
            "• Failure to analyze the displacements of the body’s center of gravity in a standing and walking mode",
            "• Failure to provide motion and biomechanical analysis charts",
          ],
        },
      ],
    },

    {
      heading: "1.2 Foot Pressure Scanner",
      paragraphs: [
        `Foot pressure scanners are able to measure the pressure exerted by your foot on the ground at any point by using pressure sensors that are arranged in one panel.`,
      ],
      image: "/Foot-2.png",
      imageAlt: "Foot pressure scanner with laptop",
      imageMaxWidth: "max-w-2xl",
      subSections: [
        {
          title: "",
          paragraphs: [
            `The foot pressure scanner is a device with a thickness of 5-10 mm, a width of 40-50 cm, and different lengths, which is placed on the floor in the examination room and the patient can stand or walk on it.`,
            `The foot pressure scanner surface is covered with thousands of small pressure-measuring sensors. Each of these sensors can measure and record the pressure applied from the foot to the ground separately. As a result, your foot pressure data is scanned and captured with high accuracy, resolution, and speed.`,
            `Using the foot pressure scanner, the feet are scanned while walking and standing. This type of foot analysis provides the doctor with a wealth of information about the skeletal structure inside the foot, the pressure points of the sole, the type of arch of the foot, and problems and abnormalities while walking. Therefore, a complete examination of the foot and investigation of skeletal abnormalities related to the foot is performed by this device.`,
            `In general, foot pressure scanner represents a complete specialized report to the specialist (depending on the brand of the device), and interpreting the outputs of the foot pressure scanner requires training.`,
          ],
        },
        {
          title: "Advantages of foot pressure scanner:",
          paragraphs: [
            "• Scanning the foot sole while standing on both feet at the same time",
            "• Scanning the foot soles while walking and running",
            "• The possibility of accurate diagnosis of at-risk points in diabetic patients’ foot and the representation of off-loading and preventive insoles",
            "• Examining knee and hip problems and abnormalities",
            "• Numerical information with high resolution from any regions of the foot",
            "• Segment ability of the foot sole automatically and diagnosis of musculoskeletal abnormalities in the foot",
            "• The possibility of designing medical insoles that are accurate and compatible with the problems and abnormalities in patient feet by using the results of foot pressure scan",
            "• Detect the uneven weight distribution on the feet soles",
            "• It is possible to check the displacements of the body’s center of gravity while standing and walking",
            "• Presentation of movement and biomedical analysis diagrams with high accuracy",
          ],
        },
        {
          title: "Disadvantages of the foot pressure scanner:",
          paragraphs: ["• They are more expensive than optical scanners"],
        },
      ],
    },

    {
      heading: "1.2.1 Gait analysis",
      paragraphs: [
        `The most advanced type of foot pressure scanner with the ability to fully analyze a step and provide accurate data from the walking pattern is called gait analysis system.`,
      ],
      image: "/Foot-3.png",
      imageAlt: "Gait analysis system",
      imageMaxWidth: "max-w-2xl",
      subSections: [
        {
          title: "",
          paragraphs: [
            `Foot scan using Gait Analysis System, obviously illustrate the displacements of the body’s center of gravity, the phase difference between two feet, the distance between two feet, the length of steps and strides, and detailed kinetic diagrams, in addition to the foot pressure scanning results.`,
            `Foot scanning is done with higher speed and accuracy by using a gait analysis system. As a result, more accurate information is provided. Gait analysis system helps save time in crowded clinics.`,
          ],
        },
      ],
    },

    {
      heading: "1.3 3D foot scanner",
      paragraphs: [
        `3D foot scanner provides a 3D model of the foot. This 3D foot model has complete information about the dimensions and sizes of the foot and foot arch.`,
      ],
      image: "/Foot-4.png",
      imageAlt: "3D foot scanner output and scanning",
      imageMaxWidth: "max-w-3xl",
      subSections: [
        {
          title: "",
          paragraphs: [
            `3D foot scanners perform the scan in full weight, semi-weight and non-weight position. The patient puts his foot on the 3D foot scanner screen and keeps it for a few seconds. Foot sole is scanned by laser lines, and the 3D output is saved in the software database.`,
            `The laser beam used in this device for scanning does not cause any harm to the patient.`,
            `In fact, whenever we need a foot mold and the dimensions and sizes of the feet are of great importance to us, we should use 3D foot scanners. Years ago, this foot molding was done using plaster. In addition to being time-consuming and difficult, the use of plaster is less accurate compared to 3D scanners, and it is not possible to mold in the weight-bearing mode.`,
          ],
        },
        {
          title: "Advantages of 3d foot scanner:",
          paragraphs: [
            "• Extracting the model of the foot sole and, as a result, the arch height",
            "• Scanning the foot in full weight, semi-weight, and non-weight-bearing positions",
            "• Measuring the foot’ length and width with high accuracy",
            "• 3D foot scan representation",
            "• Automatic detection of foot arch type",
          ],
        },
        {
          title: "Disadvantages of 3d foot scanner:",
          paragraphs: [
            "• Impossibility of diagnosing foot structural problems (internal parts)",
            "• Lack of dynamic test coverage",
            "• Expensive",
          ],
        },
      ],
    },

    {
      heading:
        "2. What is meant by foot scanning, in fact, which one of the foot scanners is used?",
      paragraphs: [
        `When we say “foot scan device”, we mean any device by which an optical scan, pressure scan, or 3D scan is obtained from the foot sole. In general, any type of scan in which the foot sole is evaluated and assessed with an accuracy is called a “foot scan.” Therefore, paying attention to the needs of patients and using the right scanner for scanning the patient’s foot is so important.`,
      ],
    },

    {
      heading:
        "3. Which method is more suitable for diagnosing and evaluating the abnormality of the foot sole?",
      paragraphs: [
        `The foot pressure scanner and the gait analysis device are the best choices for diagnosing and evaluating foot abnormalities. The internal structure of the patient’s foot can be completely and accurately determined with these devices, and the data collected can then be used to guide the treatment process.`,
      ],
    },

    {
      heading: "4. Which foot scanners are more suitable for making insoles?",
      paragraphs: [
        `The specialist must first precisely assess the problem and abnormality of the foot before designing a suitable medical insole for a patient. At the other hand, the design will be based on the patient’s exact foot dimensions and size. This suggests that a foot pressure scan followed by a 3D foot scan is the ideal foot scanning method for producing medical insoles.`,
        `The insole that is created by combining the data from foot pressure scanner and 3D foot scanner has the best scientific rating and the highest level of customer satisfaction.`,
      ],
      image: "/Foot-5.png",
      imageAlt: "Foot pressure scan for insoles",
      imageMaxWidth: "max-w-3xl",
      subSections: [
        {
          title: "4-1. Is it possible to design a medical insole with a 3D foot scanner?",
          paragraphs: [
            `If a thorough history is obtained from the patient, the patient’s foot is thoroughly examined, and any potential foot sole anomalies are diagnosed, designing a 3D scan of the foot sole is possible. When constructing medical insoles, 3D foot scanning will be highly helpful and sufficient.`,
          ],
        },
      ],
    },

    {
      heading: "",
      paragraphs: [],
      image: "/Foot-1.png",
      imageAlt: "3D model in software",
      imageMaxWidth: "max-w-3xl",
    },

    {
      heading: "5. The price of foot scanner",
      paragraphs: [
        `One of the main concerns for both clinic owners and specialists is the cost of foot scanners. The price difference for foot scanners can vary significantly. In the previous sections, we attempted to provide a brief comparison of the capabilities of several types of foot scanners. But in this section, we expand on the important subject of price.`,
        `Cost vs. Performance`,
        `“Cost vs. performance” is an issue that requires awareness. With the progress of clinics and the improvement of service quality level, the need for equipment with more capabilities also arises. Let’s categorize foot scanning equipment into two areas: “Diagnosis” and “Medical Insole Design”.`,
        `In the “diagnostic” area, the purpose of the foot scan is to analyze the foot’s health and pressure, walking, balance, detect regions that are susceptible to ulcers and wounds, analyzing the average and maximum of foot pressure to find chronic foot and ankle pain. Then a complete and accurate report is presented to the specialists.`,
        `In the field of “medical insole design”, the purpose of foot scan is to collect information on foot dimensions, foot arch type, foot arch length, foot arch height, foot margins measurement.`,
        `Now the main question is whether this information is enough to design custom medical insoles? Without proper understanding of the foot structure health, gait analysis, the average and maximum of the sole of the foot, etc.`,
        `The answer is definitely “no”. Without complete diagnostic information and based solely on information on foot dimensions, it is not possible to design a medically approved and scientific insole.`,
      ],
    },

    {
      heading: "6. Choosing the right foot scanner that is required?",
      paragraphs: [
        `With these explanations, you can consider that optical scanners, despite their low price, do not provide you with complete information either in the field of “diagnosis” or in the field of “insole design”.`,
        `Foot pressure scanner, without a doubt, is the best option. Three tests are run on this scanner: static, dynamic, and static balance. They offer comprehensive diagnostic reports that vary greatly. Because this scanner gives diagnostic data as well as the dimensions of the foot soles that are in contact with the ground, it is simple to use for insole design (especially while walking). The foot clinics would receive their responses in the “diagnostic” and “insole design” fields.`,
        `Foot pressure scanners are definitely more expensive than optical scanners, but they also offer more efficiency, a more detailed view, a quicker return on investment, and increased patient trust in the clinics.`,
      ],
    },

    {
      heading: "7. What is the efficiency of 3D foot scanners?",
      paragraphs: [
        `3D foot scanners are foot modeling devices. The main reasons for foot modeling are accurate measurement of all aspects of the foot sole. Using this information, orthotic and orthopedic insoles and shoes, and all kinds of foot accessories are performed with very high precision. If we need maximum accuracy in the design of medical insoles, we use the total information from the pressure scanner (in the diagnostic) and the information from the 3D foot scanner (in the foot dimension) at the same time.`,
      ],
    },

    {
      heading: "8. Important considerations for choosing a foot scanner",
      paragraphs: [
        `1. Be careful to match your needs with the outputs that the device is able to generate. The above texts specify how foot scanners should be used. As a result, we made an attempt to compare various foot scanners so that users may use the appropriate foot scanner for the appropriate purpose.`,
        `More complete, comprehensive and detailed report in a foot scanner, indicates the manufacturer’s awareness of the requirements of specialists, the device’s level of technology, and the manufacturer’s level of scientific knowledge.`,
        `2. Customer service and product warranties are very important factors to consider when selecting a medical device. Customers are strongly satisfied by having a full-time support team that is constantly available, knowledgeable, experienced, and familiar with their needs. In the event that there are any issues with the equipment’s operation, it is also crucial to guarantee the supply of parts and quick system repairs.`,
        `3. The manufacturer is attending to the needs of the consumer by analyzing the progress of the product and giving regular updates. It can be very helpful in ensuring the product to know the history of the business and the quality of the products.`,
      ],
    },
  ],
}
];

export const getArticleBySlug = (slug?: string) =>
  ARTICLES.find((a) => a.slug === slug);